#!/bin/bash
# Benchmark sweep across circuits, approaches, and GPU targets.
#
# Usage:
#   ./scripts/bench_sweep.sh <approach> [shots] [gpu_partition]
#
# Approaches: svm, compiled, per-op, graph, split, persistent, svm-opt
# GPU partitions: mi300x, mi300x-es, mi325x, mi350x-es
#
# Output: results/<approach>_<gpu>_<timestamp>.csv
#
# The sweep covers the circuits in tests/fixtures/sweep/ generated by
# generate_sweep_circuits.py.

set -euo pipefail

APPROACH="${1:-svm}"
SHOTS="${2:-1000000}"
PARTITION="${3:-mi300x-es}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTDIR="results"
OUTFILE="${OUTDIR}/${APPROACH}_${PARTITION}_${TIMESTAMP}.csv"
MANIFEST="tests/fixtures/sweep/manifest.txt"
BINARY="build-gpu/run_gpu"

mkdir -p "$OUTDIR"

# Map approach to CLI flag
case "$APPROACH" in
    svm)        FLAG="--interpreted" ;;
    compiled)   FLAG="--compiled" ;;
    per-op)     FLAG="--per-op" ;;
    graph)      FLAG="--graph" ;;
    split)      FLAG="--split" ;;
    persistent) FLAG="--persistent" ;;
    svm-opt)    FLAG="--svm-opt" ;;
    *)          echo "Unknown approach: $APPROACH"; exit 1 ;;
esac

# CSV header
echo "approach,partition,circuit,qubits,t_gates,depth_rounds,peak_rank,shots,passed,logical_errors,sample_seconds,shots_per_second,discard_rate" > "$OUTFILE"

# Determine GPU arch based on partition
case "$PARTITION" in
    mi300x|mi300x-es) ARCH="gfx942" ;;
    mi325x)           ARCH="gfx942" ;;  # MI325X is same ISA
    mi350x-es)        ARCH="gfx950" ;;  # MI350X uses gfx950
    *)                ARCH="gfx942" ;;
esac

echo "=== Benchmark sweep: approach=$APPROACH partition=$PARTITION shots=$SHOTS ==="
echo "Output: $OUTFILE"
echo ""

# Read manifest and run each circuit
COUNT=0
TOTAL=$(grep -v "^#" "$MANIFEST" | wc -l)
while IFS=' ' read -r FNAME NQ NT ND; do
    [[ "$FNAME" == "#"* ]] && continue
    COUNT=$((COUNT + 1))

    CIRCUIT="tests/fixtures/sweep/$FNAME"
    if [ ! -f "$CIRCUIT" ]; then
        echo "[$COUNT/$TOTAL] SKIP (not found): $CIRCUIT"
        continue
    fi

    echo -n "[$COUNT/$TOTAL] $FNAME (q=$NQ t=$NT d=$ND) ... "

    # Run and extract JSON fields
    OUTPUT=$($BINARY --circuit "$CIRCUIT" --shots "$SHOTS" --arch "$ARCH" $FLAG 2>&1) || {
        echo "FAILED"
        echo "$APPROACH,$PARTITION,$FNAME,$NQ,$NT,$ND,-1,$SHOTS,0,0,0,0,0" >> "$OUTFILE"
        continue
    }

    PEAK_RANK=$(echo "$OUTPUT" | grep '"peak_rank"' | head -1 | grep -o '[0-9]*')
    PASSED=$(echo "$OUTPUT" | grep '"passed_shots"' | head -1 | grep -o '[0-9]*')
    LOGICAL=$(echo "$OUTPUT" | grep '"logical_errors"' | head -1 | grep -o '[0-9]*')
    SAMPLE_SEC=$(echo "$OUTPUT" | grep '"sample_seconds"' | head -1 | grep -oE '[0-9]+\.[0-9eE+\-]+')
    SPS=$(echo "$OUTPUT" | grep '"shots_per_second_sampling_only"' | head -1 | grep -oE '[0-9]+\.[0-9eE+\-]+')
    DISCARD=$(echo "$OUTPUT" | grep '"discard_rate"' | head -1 | grep -oE '[0-9]+\.[0-9eE+\-]+')

    echo "${SPS} shots/s (rank=$PEAK_RANK)"
    echo "$APPROACH,$PARTITION,$FNAME,$NQ,$NT,$ND,$PEAK_RANK,$SHOTS,$PASSED,$LOGICAL,$SAMPLE_SEC,$SPS,$DISCARD" >> "$OUTFILE"

done < "$MANIFEST"

echo ""
echo "=== Done: $COUNT circuits benchmarked ==="
echo "Results: $OUTFILE"
