#define V2_NOISE_ATTR __attribute__((noinline))
#include "clifft/gpu/mlir/v2/v2_ops.h"

static void spec_body(V2State* st, CV2Complex* v, CV2Complex* scratch,
                      u32 amp_capacity, u64 shot_id, u32 num_observables, u64 seed,
                      CV2BlockCounts* block_counts,
                      const CV2FusedU2Entry* fused_u2, const CV2FusedU4Entry* fused_u4,
                      const u32* observable_offsets, const u32* observable_targets,
                      const CV2NoiseSite* noise_sites, const CV2Channel* noise_channels,
                      const double* noise_hazards, u32 num_noise_sites,
                      const CV2Mask* pauli_masks, const CV2ReadoutNoise* readout_noise,
                      const u32* detector_offsets, const u32* detector_targets,
                      u32 expected_obs_mask) {
    v2_shot_init(st, v, amp_capacity, shot_id, num_observables, seed, noise_hazards, num_noise_sites);
    v2_op_meas_dormant_static(st, 6u, 124u, 0u);
    v2_op_meas_dormant_static(st, 8u, 123u, 0u);
    v2_op_meas_dormant_static(st, 12u, 122u, 0u);
    v2_op_meas_dormant_random(st, 17u, 121u, 0u);
    v2_op_meas_dormant_random(st, 5u, 120u, 0u);
    v2_op_meas_dormant_random(st, 0u, 119u, 0u);
    v2_op_meas_dormant_random(st, 18u, 118u, 0u);
    v2_op_meas_dormant_random(st, 4u, 117u, 0u);
    v2_op_meas_dormant_random(st, 2u, 116u, 0u);
    v2_op_meas_dormant_random(st, 3u, 115u, 0u);
    v2_op_meas_dormant_random(st, 13u, 114u, 0u);
    v2_op_meas_dormant_random(st, 11u, 113u, 0u);
    v2_op_meas_dormant_random(st, 7u, 112u, 0u);
    v2_op_apply_pauli(st, pauli_masks, 0u, 112u);
    v2_op_apply_pauli(st, pauli_masks, 1u, 113u);
    v2_op_apply_pauli(st, pauli_masks, 2u, 114u);
    v2_op_apply_pauli(st, pauli_masks, 3u, 115u);
    v2_op_apply_pauli(st, pauli_masks, 4u, 116u);
    v2_op_apply_pauli(st, pauli_masks, 5u, 117u);
    v2_op_apply_pauli(st, pauli_masks, 6u, 118u);
    v2_op_apply_pauli(st, pauli_masks, 7u, 119u);
    v2_op_apply_pauli(st, pauli_masks, 8u, 120u);
    v2_op_apply_pauli(st, pauli_masks, 9u, 121u);
    v2_op_apply_pauli(st, pauli_masks, 10u, 122u);
    v2_op_apply_pauli(st, pauli_masks, 11u, 123u);
    v2_op_apply_pauli(st, pauli_masks, 12u, 124u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 0u, 401u);
    v2_op_frame_cnot(st, 3u, 11u);
    v2_op_frame_cnot(st, 3u, 13u);
    v2_op_frame_cz(st, 3u, 6u);
    v2_op_frame_cz(st, 3u, 8u);
    v2_op_frame_swap(st, 3u, 0u);
    v2_op_frame_h(st, 0u);
    v2_op_expand_t(st, v, 0u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 401u, 165u);
    v2_op_meas_dormant_static(st, 3u, 125u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 566u);
    v2_op_meas_dormant_static(st, 5u, 127u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 567u, 3u);
    v2_op_frame_cnot(st, 2u, 7u);
    v2_op_frame_cnot(st, 2u, 11u);
    v2_op_frame_cz(st, 2u, 6u);
    v2_op_meas_dormant_random(st, 2u, 128u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 570u, 2u);
    v2_op_frame_cnot(st, 4u, 7u);
    v2_op_frame_cnot(st, 4u, 13u);
    v2_op_frame_cz(st, 4u, 8u);
    v2_op_meas_dormant_random(st, 4u, 130u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 572u);
    v2_op_meas_dormant_static(st, 9u, 131u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 573u, 3u);
    v2_op_meas_dormant_static(st, 18u, 126u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 576u, 6u);
    v2_op_frame_cnot(st, 7u, 11u);
    v2_op_frame_cnot(st, 7u, 13u);
    v2_op_frame_cnot(st, 7u, 17u);
    v2_op_frame_cz(st, 7u, 12u);
    v2_op_meas_dormant_random(st, 7u, 129u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 582u, 23u);
    v2_op_apply_pauli(st, pauli_masks, 13u, 125u);
    v2_op_apply_pauli(st, pauli_masks, 14u, 126u);
    v2_op_apply_pauli(st, pauli_masks, 15u, 127u);
    v2_op_apply_pauli(st, pauli_masks, 16u, 128u);
    v2_op_apply_pauli(st, pauli_masks, 17u, 129u);
    v2_op_apply_pauli(st, pauli_masks, 18u, 130u);
    v2_op_apply_pauli(st, pauli_masks, 19u, 131u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 605u, 308u);
    v2_op_meas_dormant_static(st, 11u, 4u, 0u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_meas_dormant_static(st, 2u, 0u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 913u);
    v2_op_meas_dormant_static(st, 13u, 6u, 0u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_frame_cnot(st, 8u, 2u);
    v2_op_frame_cnot(st, 9u, 2u);
    v2_op_meas_dormant_static(st, 2u, 2u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 914u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 5u, 0u);
    v2_op_meas_dormant_static(st, 12u, 1u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 915u, 4u);
    v2_op_meas_dormant_static(st, 9u, 3u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 919u, 32u);
    v2_op_readout_noise(st, readout_noise, 0u);
    v2_op_readout_noise(st, readout_noise, 1u);
    v2_op_readout_noise(st, readout_noise, 2u);
    v2_op_readout_noise(st, readout_noise, 3u);
    v2_op_readout_noise(st, readout_noise, 4u);
    v2_op_readout_noise(st, readout_noise, 5u);
    v2_op_readout_noise(st, readout_noise, 6u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 951u);
    v2_op_frame_cz(st, 8u, 11u);
    v2_op_frame_cz(st, 8u, 13u);
    v2_op_frame_cz(st, 8u, 17u);
    v2_op_meas_dormant_random(st, 8u, 134u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 952u);
    v2_op_frame_cnot(st, 7u, 12u);
    v2_op_frame_cz(st, 7u, 18u);
    v2_op_meas_dormant_random(st, 7u, 132u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 953u);
    v2_op_frame_cnot(st, 2u, 0u);
    v2_op_frame_cnot(st, 2u, 4u);
    v2_op_frame_cnot(st, 2u, 6u);
    v2_op_frame_cz(st, 2u, 5u);
    v2_op_frame_cz(st, 2u, 8u);
    v2_op_frame_cz(st, 2u, 11u);
    v2_op_frame_cz(st, 2u, 17u);
    v2_op_meas_dormant_random(st, 2u, 136u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 954u, 2u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 135u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 956u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 133u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 957u, 3u);
    v2_op_meas_dormant_random(st, 1u, 137u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 960u, 33u);
    v2_op_apply_pauli(st, pauli_masks, 20u, 132u);
    v2_op_apply_pauli(st, pauli_masks, 21u, 133u);
    v2_op_apply_pauli(st, pauli_masks, 22u, 134u);
    v2_op_apply_pauli(st, pauli_masks, 23u, 135u);
    v2_op_apply_pauli(st, pauli_masks, 24u, 136u);
    v2_op_apply_pauli(st, pauli_masks, 25u, 137u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 993u, 42u);
    v2_op_frame_swap(st, 3u, 1u);
    v2_op_frame_h(st, 1u);
    v2_op_expand_t(st, v, 1u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1035u);
    v2_op_frame_cz(st, 5u, 0u);
    v2_op_frame_cz(st, 5u, 1u);
    v2_op_frame_swap(st, 5u, 2u);
    v2_op_frame_h(st, 2u);
    v2_op_expand_t(st, v, 2u, 2u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1036u);
    v2_op_frame_cz(st, 18u, 0u);
    v2_op_frame_cz(st, 18u, 2u);
    v2_op_frame_cz(st, 18u, 4u);
    v2_op_frame_cz(st, 18u, 6u);
    v2_op_frame_cz(st, 18u, 9u);
    v2_op_frame_cz(st, 18u, 12u);
    v2_op_frame_swap(st, 18u, 3u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1037u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 9u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1038u);
    v2_op_array_multi_cnot(st, v, 4u, 1u, 12ull);
    v2_op_frame_cnot(st, 4u, 1u);
    v2_op_frame_cnot(st, 6u, 1u);
    v2_op_array_t(st, v, 4u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1039u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 12ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1040u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 10ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1041u, 152u);
    v2_op_array_cnot(st, v, 4u, 0u, 1u);
    v2_op_array_cnot(st, v, 4u, 0u, 2u);
    v2_op_array_cnot(st, v, 4u, 0u, 3u);
    v2_op_frame_cz(st, 0u, 5u);
    v2_op_frame_cz(st, 0u, 7u);
    v2_op_frame_cz(st, 0u, 11u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_frame_cz(st, 0u, 18u);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 0u, 3u, 7u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1193u, 40u);
    v2_op_readout_noise(st, readout_noise, 7u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1233u);
    v2_op_meas_dormant_static(st, 3u, 138u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1234u, 41u);
    v2_op_apply_pauli(st, pauli_masks, 26u, 138u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1275u, 198u);
    v2_op_frame_cz(st, 3u, 0u);
    v2_op_frame_cz(st, 3u, 1u);
    v2_op_frame_cz(st, 3u, 2u);
    v2_op_frame_cz(st, 3u, 4u);
    v2_op_frame_cz(st, 3u, 6u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1473u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 10ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1474u);
    v2_op_array_multi_cnot(st, v, 4u, 1u, 12ull);
    v2_op_frame_cnot(st, 4u, 1u);
    v2_op_frame_cnot(st, 6u, 1u);
    v2_op_array_t(st, v, 4u, 1u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1475u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 14ull);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1476u);
    v2_op_array_cnot(st, v, 4u, 2u, 0u);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1477u);
    v2_op_array_cnot(st, v, 4u, 3u, 2u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_frame_cnot(st, 12u, 2u);
    v2_op_array_t(st, v, 4u, 2u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1478u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1479u, 2u);
    v2_op_meas_dormant_static(st, 18u, 13u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1481u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 11u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1482u, 3u);
    v2_op_meas_dormant_static(st, 8u, 10u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1485u);
    v2_op_meas_dormant_static(st, 5u, 12u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1486u, 2u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 9u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1488u, 4u);
    v2_op_meas_dormant_static(st, 7u, 8u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1492u, 23u);
    v2_op_readout_noise(st, readout_noise, 8u);
    v2_op_readout_noise(st, readout_noise, 9u);
    v2_op_readout_noise(st, readout_noise, 10u);
    v2_op_readout_noise(st, readout_noise, 11u);
    v2_op_readout_noise(st, readout_noise, 12u);
    v2_op_readout_noise(st, readout_noise, 13u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1515u, 17u);
    v2_op_meas_dormant_static(st, 15u, 151u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1532u);
    v2_op_meas_dormant_random(st, 16u, 142u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1533u, 2u);
    v2_op_meas_dormant_static(st, 19u, 145u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1535u, 2u);
    v2_op_meas_dormant_static(st, 21u, 153u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1537u);
    v2_op_meas_dormant_static(st, 22u, 152u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1538u);
    v2_op_meas_dormant_static(st, 23u, 150u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1539u, 2u);
    v2_op_meas_dormant_static(st, 25u, 146u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1541u);
    v2_op_meas_dormant_random(st, 26u, 139u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1542u);
    v2_op_meas_dormant_random(st, 27u, 144u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1543u);
    v2_op_meas_dormant_random(st, 28u, 143u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1544u);
    v2_op_meas_dormant_static(st, 29u, 154u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1545u, 3u);
    v2_op_meas_dormant_static(st, 32u, 147u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1548u);
    v2_op_meas_dormant_random(st, 33u, 140u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1549u);
    v2_op_meas_dormant_static(st, 34u, 155u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1550u, 2u);
    v2_op_meas_dormant_random(st, 36u, 141u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1552u, 2u);
    v2_op_meas_dormant_static(st, 38u, 148u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1554u, 2u);
    v2_op_meas_dormant_static(st, 40u, 149u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1556u);
    v2_op_apply_pauli(st, pauli_masks, 27u, 139u);
    v2_op_apply_pauli(st, pauli_masks, 28u, 140u);
    v2_op_apply_pauli(st, pauli_masks, 29u, 141u);
    v2_op_apply_pauli(st, pauli_masks, 30u, 142u);
    v2_op_apply_pauli(st, pauli_masks, 31u, 143u);
    v2_op_apply_pauli(st, pauli_masks, 32u, 144u);
    v2_op_apply_pauli(st, pauli_masks, 33u, 145u);
    v2_op_apply_pauli(st, pauli_masks, 34u, 146u);
    v2_op_apply_pauli(st, pauli_masks, 35u, 147u);
    v2_op_apply_pauli(st, pauli_masks, 36u, 148u);
    v2_op_apply_pauli(st, pauli_masks, 37u, 149u);
    v2_op_apply_pauli(st, pauli_masks, 38u, 150u);
    v2_op_apply_pauli(st, pauli_masks, 39u, 151u);
    v2_op_apply_pauli(st, pauli_masks, 40u, 152u);
    v2_op_apply_pauli(st, pauli_masks, 41u, 153u);
    v2_op_apply_pauli(st, pauli_masks, 42u, 154u);
    v2_op_apply_pauli(st, pauli_masks, 43u, 155u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1557u, 116u);
    v2_op_meas_dormant_static(st, 15u, 18u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1673u);
    v2_op_meas_dormant_static(st, 23u, 17u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1674u);
    v2_op_meas_dormant_static(st, 25u, 14u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1675u);
    v2_op_meas_dormant_static(st, 29u, 16u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1676u);
    v2_op_meas_dormant_static(st, 32u, 15u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1677u, 32u);
    v2_op_readout_noise(st, readout_noise, 14u);
    v2_op_readout_noise(st, readout_noise, 15u);
    v2_op_readout_noise(st, readout_noise, 16u);
    v2_op_readout_noise(st, readout_noise, 17u);
    v2_op_readout_noise(st, readout_noise, 18u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1709u);
    v2_op_frame_cnot(st, 19u, 25u);
    v2_op_frame_cz(st, 19u, 26u);
    v2_op_meas_dormant_random(st, 19u, 158u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1710u);
    v2_op_meas_dormant_static(st, 32u, 167u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1711u);
    v2_op_frame_cnot(st, 21u, 29u);
    v2_op_frame_cz(st, 21u, 28u);
    v2_op_meas_dormant_random(st, 21u, 157u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1712u);
    v2_op_meas_dormant_static(st, 23u, 169u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1713u);
    v2_op_frame_cnot(st, 15u, 22u);
    v2_op_frame_cz(st, 15u, 16u);
    v2_op_meas_dormant_random(st, 15u, 160u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1714u, 3u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 164u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1717u, 2u);
    v2_op_meas_dormant_static(st, 13u, 163u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1719u, 2u);
    v2_op_frame_cz(st, 8u, 4u);
    v2_op_frame_cz(st, 8u, 6u);
    v2_op_frame_cz(st, 8u, 9u);
    v2_op_meas_dormant_random(st, 8u, 173u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1721u, 2u);
    v2_op_frame_cz(st, 5u, 0u);
    v2_op_meas_dormant_random(st, 5u, 172u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1723u, 4u);
    v2_op_frame_cnot(st, 13u, 11u);
    v2_op_frame_cnot(st, 17u, 11u);
    v2_op_meas_dormant_static(st, 11u, 162u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1727u, 2u);
    v2_op_meas_dormant_random(st, 14u, 161u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1729u, 3u);
    v2_op_frame_cz(st, 7u, 0u);
    v2_op_frame_cz(st, 7u, 12u);
    v2_op_meas_dormant_random(st, 7u, 171u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1732u, 2u);
    v2_op_meas_dormant_static(st, 20u, 170u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1734u, 3u);
    v2_op_meas_dormant_random(st, 24u, 159u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1737u, 5u);
    v2_op_meas_dormant_static(st, 31u, 168u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1742u, 3u);
    v2_op_meas_dormant_static(st, 35u, 166u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1745u, 2u);
    v2_op_meas_dormant_random(st, 37u, 156u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1747u, 4u);
    v2_op_meas_dormant_static(st, 41u, 165u, 0u);
    v2_op_apply_pauli(st, pauli_masks, 44u, 156u);
    v2_op_apply_pauli(st, pauli_masks, 45u, 157u);
    v2_op_apply_pauli(st, pauli_masks, 46u, 158u);
    v2_op_apply_pauli(st, pauli_masks, 47u, 159u);
    v2_op_apply_pauli(st, pauli_masks, 48u, 160u);
    v2_op_apply_pauli(st, pauli_masks, 49u, 161u);
    v2_op_apply_pauli(st, pauli_masks, 50u, 162u);
    v2_op_apply_pauli(st, pauli_masks, 51u, 163u);
    v2_op_apply_pauli(st, pauli_masks, 52u, 164u);
    v2_op_apply_pauli(st, pauli_masks, 53u, 165u);
    v2_op_apply_pauli(st, pauli_masks, 54u, 166u);
    v2_op_apply_pauli(st, pauli_masks, 55u, 167u);
    v2_op_apply_pauli(st, pauli_masks, 56u, 168u);
    v2_op_apply_pauli(st, pauli_masks, 57u, 169u);
    v2_op_apply_pauli(st, pauli_masks, 58u, 170u);
    v2_op_apply_pauli(st, pauli_masks, 59u, 171u);
    v2_op_apply_pauli(st, pauli_masks, 60u, 172u);
    v2_op_apply_pauli(st, pauli_masks, 61u, 173u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1751u, 244u);
    v2_op_array_cnot(st, v, 4u, 1u, 3u);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 1u, 3u, 36u, 0u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_frame_cnot(st, 8u, 4u);
    v2_op_meas_dormant_static(st, 4u, 27u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1995u);
    v2_op_array_cnot(st, v, 3u, 1u, 2u);
    v2_op_frame_cz(st, 1u, 3u);
    v2_op_swap_meas_interfere(st, v, scratch, 3u, 1u, 2u, 35u, 0u);
    v2_op_frame_cnot(st, 5u, 4u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_frame_cnot(st, 8u, 4u);
    v2_op_meas_dormant_static(st, 4u, 26u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1996u);
    v2_op_frame_cz(st, 0u, 2u);
    v2_op_frame_cz(st, 0u, 11u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_frame_cz(st, 0u, 14u);
    v2_op_frame_cz(st, 0u, 18u);
    v2_op_frame_cz(st, 0u, 26u);
    v2_op_swap_meas_interfere(st, v, scratch, 2u, 0u, 1u, 34u, 0u);
    v2_op_frame_cnot(st, 12u, 7u);
    v2_op_frame_cnot(st, 25u, 7u);
    v2_op_meas_dormant_static(st, 7u, 25u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1997u);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 12u, 22u);
    v2_op_frame_cnot(st, 12u, 25u);
    v2_op_frame_cnot(st, 12u, 29u);
    v2_op_frame_cnot(st, 12u, 34u);
    v2_op_frame_cz(st, 12u, 13u);
    v2_op_frame_cz(st, 12u, 15u);
    v2_op_frame_cz(st, 12u, 16u);
    v2_op_frame_cz(st, 12u, 19u);
    v2_op_frame_cz(st, 12u, 21u);
    v2_op_frame_cz(st, 12u, 26u);
    v2_op_frame_cz(st, 12u, 27u);
    v2_op_frame_cz(st, 12u, 28u);
    v2_op_meas_dormant_random(st, 12u, 33u, 0u);
    v2_op_frame_cnot(st, 16u, 26u);
    v2_op_frame_cnot(st, 16u, 27u);
    v2_op_frame_cnot(st, 16u, 28u);
    v2_op_frame_cz(st, 16u, 0u);
    v2_op_frame_cz(st, 16u, 6u);
    v2_op_frame_cz(st, 16u, 20u);
    v2_op_meas_dormant_random(st, 16u, 24u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1998u);
    v2_op_frame_cnot(st, 28u, 14u);
    v2_op_meas_dormant_static(st, 14u, 32u, 0u);
    v2_op_frame_cnot(st, 29u, 22u);
    v2_op_meas_dormant_static(st, 22u, 23u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 1999u);
    v2_op_frame_cnot(st, 29u, 0u);
    v2_op_frame_cnot(st, 29u, 34u);
    v2_op_frame_cnot(st, 29u, 38u);
    v2_op_frame_cnot(st, 29u, 40u);
    v2_op_frame_cz(st, 29u, 1u);
    v2_op_frame_cz(st, 29u, 2u);
    v2_op_frame_cz(st, 29u, 12u);
    v2_op_frame_cz(st, 29u, 13u);
    v2_op_frame_cz(st, 29u, 14u);
    v2_op_frame_cz(st, 29u, 15u);
    v2_op_frame_cz(st, 29u, 17u);
    v2_op_frame_cz(st, 29u, 19u);
    v2_op_frame_cz(st, 29u, 21u);
    v2_op_frame_cz(st, 29u, 24u);
    v2_op_frame_cz(st, 29u, 27u);
    v2_op_frame_cz(st, 29u, 33u);
    v2_op_frame_cz(st, 29u, 36u);
    v2_op_meas_dormant_random(st, 29u, 31u, 0u);
    v2_op_frame_cnot(st, 26u, 33u);
    v2_op_frame_cnot(st, 26u, 36u);
    v2_op_frame_cz(st, 26u, 25u);
    v2_op_frame_cz(st, 26u, 31u);
    v2_op_frame_cz(st, 26u, 32u);
    v2_op_meas_dormant_random(st, 26u, 22u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2000u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 33u, 21u);
    v2_op_meas_dormant_static(st, 21u, 30u, 0u);
    v2_op_frame_cnot(st, 34u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_meas_dormant_static(st, 25u, 21u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2001u);
    v2_op_frame_cnot(st, 27u, 19u);
    v2_op_frame_cnot(st, 28u, 19u);
    v2_op_meas_dormant_static(st, 19u, 29u, 0u);
    v2_op_frame_cnot(st, 35u, 34u);
    v2_op_meas_dormant_static(st, 34u, 20u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2002u);
    v2_op_frame_cnot(st, 36u, 33u);
    v2_op_meas_dormant_static(st, 33u, 28u, 0u);
    v2_op_frame_cnot(st, 38u, 32u);
    v2_op_frame_cnot(st, 40u, 32u);
    v2_op_frame_cnot(st, 41u, 32u);
    v2_op_meas_dormant_static(st, 32u, 19u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2003u, 24u);
    v2_op_readout_noise(st, readout_noise, 19u);
    v2_op_readout_noise(st, readout_noise, 20u);
    v2_op_readout_noise(st, readout_noise, 21u);
    v2_op_readout_noise(st, readout_noise, 22u);
    v2_op_readout_noise(st, readout_noise, 23u);
    v2_op_readout_noise(st, readout_noise, 24u);
    v2_op_readout_noise(st, readout_noise, 25u);
    v2_op_readout_noise(st, readout_noise, 26u);
    v2_op_readout_noise(st, readout_noise, 27u);
    v2_op_readout_noise(st, readout_noise, 28u);
    v2_op_readout_noise(st, readout_noise, 29u);
    v2_op_readout_noise(st, readout_noise, 30u);
    v2_op_readout_noise(st, readout_noise, 31u);
    v2_op_readout_noise(st, readout_noise, 32u);
    v2_op_readout_noise(st, readout_noise, 33u);
    v2_op_readout_noise(st, readout_noise, 34u);
    v2_op_readout_noise(st, readout_noise, 35u);
    v2_op_readout_noise(st, readout_noise, 36u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2027u);
    v2_op_meas_dormant_static(st, 32u, 183u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2028u);
    v2_op_meas_dormant_static(st, 34u, 184u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2029u);
    v2_op_meas_dormant_static(st, 25u, 185u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2030u);
    v2_op_meas_dormant_static(st, 26u, 186u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2031u);
    v2_op_meas_dormant_static(st, 22u, 187u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2032u);
    v2_op_meas_dormant_static(st, 16u, 188u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2033u);
    v2_op_meas_dormant_static(st, 7u, 189u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2034u);
    v2_op_meas_dormant_static(st, 4u, 190u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2035u);
    v2_op_frame_cnot(st, 5u, 4u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_frame_cnot(st, 8u, 4u);
    v2_op_meas_dormant_static(st, 4u, 191u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2036u);
    v2_op_meas_dormant_static(st, 33u, 174u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2037u);
    v2_op_meas_dormant_static(st, 19u, 175u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2038u);
    v2_op_meas_dormant_static(st, 21u, 176u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2039u);
    v2_op_meas_dormant_static(st, 29u, 177u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2040u);
    v2_op_meas_dormant_static(st, 14u, 178u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2041u);
    v2_op_meas_dormant_static(st, 12u, 179u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2042u);
    v2_op_meas_dormant_static(st, 1u, 180u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2043u);
    v2_op_meas_dormant_static(st, 2u, 181u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2044u);
    v2_op_meas_dormant_static(st, 3u, 182u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2045u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 62u, 31u);
    v2_op_apply_pauli(st, pauli_masks, 63u, 31u);
    v2_op_apply_pauli(st, pauli_masks, 64u, 33u);
    v2_op_apply_pauli(st, pauli_masks, 65u, 33u);
    v2_op_apply_pauli(st, pauli_masks, 66u, 22u);
    v2_op_apply_pauli(st, pauli_masks, 67u, 22u);
    v2_op_apply_pauli(st, pauli_masks, 68u, 22u);
    v2_op_apply_pauli(st, pauli_masks, 69u, 22u);
    v2_op_apply_pauli(st, pauli_masks, 70u, 21u);
    v2_op_apply_pauli(st, pauli_masks, 71u, 21u);
    v2_op_apply_pauli(st, pauli_masks, 72u, 25u);
    v2_op_apply_pauli(st, pauli_masks, 73u, 25u);
    v2_op_apply_pauli(st, pauli_masks, 74u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 75u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 76u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 77u, 23u);
    v2_op_apply_pauli(st, pauli_masks, 78u, 23u);
    v2_op_apply_pauli(st, pauli_masks, 79u, 174u);
    v2_op_apply_pauli(st, pauli_masks, 80u, 175u);
    v2_op_apply_pauli(st, pauli_masks, 81u, 176u);
    v2_op_apply_pauli(st, pauli_masks, 82u, 177u);
    v2_op_apply_pauli(st, pauli_masks, 83u, 178u);
    v2_op_apply_pauli(st, pauli_masks, 84u, 179u);
    v2_op_apply_pauli(st, pauli_masks, 85u, 180u);
    v2_op_apply_pauli(st, pauli_masks, 86u, 181u);
    v2_op_apply_pauli(st, pauli_masks, 87u, 182u);
    v2_op_apply_pauli(st, pauli_masks, 88u, 183u);
    v2_op_apply_pauli(st, pauli_masks, 89u, 184u);
    v2_op_apply_pauli(st, pauli_masks, 90u, 185u);
    v2_op_apply_pauli(st, pauli_masks, 91u, 186u);
    v2_op_apply_pauli(st, pauli_masks, 92u, 187u);
    v2_op_apply_pauli(st, pauli_masks, 93u, 188u);
    v2_op_apply_pauli(st, pauli_masks, 94u, 189u);
    v2_op_apply_pauli(st, pauli_masks, 95u, 190u);
    v2_op_apply_pauli(st, pauli_masks, 96u, 191u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2069u, 244u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 13u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_meas_dormant_static(st, 2u, 54u, 0u);
    v2_op_frame_cnot(st, 5u, 4u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_meas_dormant_static(st, 4u, 45u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2313u);
    v2_op_frame_cnot(st, 3u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_meas_dormant_static(st, 2u, 53u, 0u);
    v2_op_frame_cnot(st, 8u, 6u);
    v2_op_meas_dormant_static(st, 6u, 44u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2314u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_frame_cnot(st, 12u, 1u);
    v2_op_meas_dormant_static(st, 1u, 52u, 0u);
    v2_op_frame_cnot(st, 25u, 16u);
    v2_op_frame_cnot(st, 34u, 16u);
    v2_op_frame_cnot(st, 35u, 16u);
    v2_op_frame_cnot(st, 38u, 16u);
    v2_op_meas_dormant_static(st, 16u, 43u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2315u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_frame_cnot(st, 28u, 1u);
    v2_op_meas_dormant_static(st, 1u, 51u, 0u);
    v2_op_frame_cnot(st, 16u, 7u);
    v2_op_frame_cnot(st, 20u, 7u);
    v2_op_frame_cnot(st, 22u, 7u);
    v2_op_frame_cnot(st, 25u, 7u);
    v2_op_frame_cnot(st, 34u, 7u);
    v2_op_frame_cnot(st, 35u, 7u);
    v2_op_frame_cnot(st, 38u, 7u);
    v2_op_meas_dormant_static(st, 7u, 42u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2316u);
    v2_op_frame_cnot(st, 14u, 12u);
    v2_op_frame_cnot(st, 15u, 12u);
    v2_op_meas_dormant_static(st, 12u, 50u, 0u);
    v2_op_frame_cnot(st, 22u, 16u);
    v2_op_frame_cnot(st, 23u, 16u);
    v2_op_frame_cnot(st, 25u, 16u);
    v2_op_frame_cnot(st, 34u, 16u);
    v2_op_frame_cnot(st, 35u, 16u);
    v2_op_frame_cnot(st, 38u, 16u);
    v2_op_meas_dormant_static(st, 16u, 41u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2317u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_meas_dormant_static(st, 21u, 49u, 0u);
    v2_op_frame_cnot(st, 31u, 25u);
    v2_op_meas_dormant_static(st, 25u, 40u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2318u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 28u, 21u);
    v2_op_frame_cnot(st, 29u, 21u);
    v2_op_meas_dormant_static(st, 21u, 48u, 0u);
    v2_op_frame_cnot(st, 26u, 25u);
    v2_op_frame_cnot(st, 31u, 25u);
    v2_op_frame_cnot(st, 32u, 25u);
    v2_op_frame_cnot(st, 34u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_frame_cnot(st, 40u, 25u);
    v2_op_frame_cnot(st, 41u, 25u);
    v2_op_meas_dormant_static(st, 25u, 39u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2319u);
    v2_op_frame_cnot(st, 24u, 19u);
    v2_op_frame_cnot(st, 27u, 19u);
    v2_op_frame_cnot(st, 33u, 19u);
    v2_op_frame_cnot(st, 36u, 19u);
    v2_op_meas_dormant_static(st, 19u, 47u, 0u);
    v2_op_frame_cnot(st, 26u, 25u);
    v2_op_frame_cnot(st, 32u, 25u);
    v2_op_frame_cnot(st, 35u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_frame_cnot(st, 40u, 25u);
    v2_op_frame_cnot(st, 41u, 25u);
    v2_op_meas_dormant_static(st, 25u, 38u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2320u);
    v2_op_frame_cnot(st, 37u, 33u);
    v2_op_meas_dormant_static(st, 33u, 46u, 0u);
    v2_op_frame_cnot(st, 41u, 32u);
    v2_op_meas_dormant_static(st, 32u, 37u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2321u, 24u);
    v2_op_readout_noise(st, readout_noise, 37u);
    v2_op_readout_noise(st, readout_noise, 38u);
    v2_op_readout_noise(st, readout_noise, 39u);
    v2_op_readout_noise(st, readout_noise, 40u);
    v2_op_readout_noise(st, readout_noise, 41u);
    v2_op_readout_noise(st, readout_noise, 42u);
    v2_op_readout_noise(st, readout_noise, 43u);
    v2_op_readout_noise(st, readout_noise, 44u);
    v2_op_readout_noise(st, readout_noise, 45u);
    v2_op_readout_noise(st, readout_noise, 46u);
    v2_op_readout_noise(st, readout_noise, 47u);
    v2_op_readout_noise(st, readout_noise, 48u);
    v2_op_readout_noise(st, readout_noise, 49u);
    v2_op_readout_noise(st, readout_noise, 50u);
    v2_op_readout_noise(st, readout_noise, 51u);
    v2_op_readout_noise(st, readout_noise, 52u);
    v2_op_readout_noise(st, readout_noise, 53u);
    v2_op_readout_noise(st, readout_noise, 54u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2345u);
    v2_op_meas_dormant_static(st, 32u, 201u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2346u);
    v2_op_meas_dormant_static(st, 25u, 202u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2347u);
    v2_op_frame_cnot(st, 26u, 25u);
    v2_op_frame_cnot(st, 32u, 25u);
    v2_op_frame_cnot(st, 35u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_frame_cnot(st, 40u, 25u);
    v2_op_meas_dormant_static(st, 25u, 203u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2348u);
    v2_op_frame_cnot(st, 26u, 25u);
    v2_op_frame_cnot(st, 31u, 25u);
    v2_op_frame_cnot(st, 32u, 25u);
    v2_op_frame_cnot(st, 34u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_frame_cnot(st, 40u, 25u);
    v2_op_meas_dormant_static(st, 25u, 204u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2349u);
    v2_op_meas_dormant_static(st, 16u, 205u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2350u);
    v2_op_meas_dormant_static(st, 7u, 206u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2351u);
    v2_op_frame_cnot(st, 22u, 16u);
    v2_op_frame_cnot(st, 23u, 16u);
    v2_op_frame_cnot(st, 25u, 16u);
    v2_op_frame_cnot(st, 31u, 16u);
    v2_op_frame_cnot(st, 34u, 16u);
    v2_op_frame_cnot(st, 35u, 16u);
    v2_op_frame_cnot(st, 38u, 16u);
    v2_op_meas_dormant_static(st, 16u, 207u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2352u);
    v2_op_meas_dormant_static(st, 6u, 208u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2353u);
    v2_op_meas_dormant_static(st, 4u, 209u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2354u);
    v2_op_meas_dormant_static(st, 33u, 192u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2355u);
    v2_op_meas_dormant_static(st, 19u, 193u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2356u);
    v2_op_meas_dormant_static(st, 21u, 194u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2357u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 28u, 21u);
    v2_op_frame_cnot(st, 29u, 21u);
    v2_op_meas_dormant_static(st, 21u, 195u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2358u);
    v2_op_meas_dormant_static(st, 12u, 196u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2359u);
    v2_op_meas_dormant_static(st, 1u, 197u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2360u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_frame_cnot(st, 28u, 1u);
    v2_op_meas_dormant_static(st, 1u, 198u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2361u);
    v2_op_meas_dormant_static(st, 2u, 199u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2362u);
    v2_op_frame_cnot(st, 3u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_meas_dormant_static(st, 2u, 200u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2363u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 97u, 192u);
    v2_op_apply_pauli(st, pauli_masks, 98u, 193u);
    v2_op_apply_pauli(st, pauli_masks, 99u, 194u);
    v2_op_apply_pauli(st, pauli_masks, 100u, 195u);
    v2_op_apply_pauli(st, pauli_masks, 101u, 196u);
    v2_op_apply_pauli(st, pauli_masks, 102u, 197u);
    v2_op_apply_pauli(st, pauli_masks, 103u, 198u);
    v2_op_apply_pauli(st, pauli_masks, 104u, 199u);
    v2_op_apply_pauli(st, pauli_masks, 105u, 200u);
    v2_op_apply_pauli(st, pauli_masks, 106u, 201u);
    v2_op_apply_pauli(st, pauli_masks, 107u, 202u);
    v2_op_apply_pauli(st, pauli_masks, 108u, 203u);
    v2_op_apply_pauli(st, pauli_masks, 109u, 204u);
    v2_op_apply_pauli(st, pauli_masks, 110u, 205u);
    v2_op_apply_pauli(st, pauli_masks, 111u, 206u);
    v2_op_apply_pauli(st, pauli_masks, 112u, 207u);
    v2_op_apply_pauli(st, pauli_masks, 113u, 208u);
    v2_op_apply_pauli(st, pauli_masks, 114u, 209u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2387u, 244u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_meas_dormant_static(st, 2u, 72u, 0u);
    v2_op_frame_cnot(st, 5u, 4u);
    v2_op_frame_cnot(st, 8u, 4u);
    v2_op_meas_dormant_static(st, 4u, 63u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2631u);
    v2_op_frame_cnot(st, 3u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 13u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_meas_dormant_static(st, 2u, 71u, 0u);
    v2_op_frame_cnot(st, 8u, 6u);
    v2_op_meas_dormant_static(st, 6u, 62u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2632u);
    v2_op_frame_cnot(st, 12u, 1u);
    v2_op_frame_cnot(st, 14u, 1u);
    v2_op_frame_cnot(st, 15u, 1u);
    v2_op_frame_cnot(st, 28u, 1u);
    v2_op_meas_dormant_static(st, 1u, 70u, 0u);
    v2_op_frame_cnot(st, 22u, 20u);
    v2_op_frame_cnot(st, 25u, 20u);
    v2_op_frame_cnot(st, 31u, 20u);
    v2_op_frame_cnot(st, 34u, 20u);
    v2_op_frame_cnot(st, 35u, 20u);
    v2_op_frame_cnot(st, 38u, 20u);
    v2_op_meas_dormant_static(st, 20u, 61u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2633u);
    v2_op_frame_cnot(st, 14u, 11u);
    v2_op_frame_cnot(st, 15u, 11u);
    v2_op_frame_cnot(st, 28u, 11u);
    v2_op_meas_dormant_static(st, 11u, 69u, 0u);
    v2_op_frame_cnot(st, 16u, 7u);
    v2_op_frame_cnot(st, 22u, 7u);
    v2_op_frame_cnot(st, 23u, 7u);
    v2_op_meas_dormant_static(st, 7u, 60u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2634u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_frame_cnot(st, 14u, 1u);
    v2_op_frame_cnot(st, 28u, 1u);
    v2_op_meas_dormant_static(st, 1u, 68u, 0u);
    v2_op_frame_cnot(st, 22u, 7u);
    v2_op_frame_cnot(st, 25u, 7u);
    v2_op_frame_cnot(st, 31u, 7u);
    v2_op_frame_cnot(st, 34u, 7u);
    v2_op_frame_cnot(st, 35u, 7u);
    v2_op_frame_cnot(st, 38u, 7u);
    v2_op_meas_dormant_static(st, 7u, 59u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2635u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 28u, 21u);
    v2_op_meas_dormant_static(st, 21u, 67u, 0u);
    v2_op_frame_cnot(st, 31u, 25u);
    v2_op_frame_cnot(st, 32u, 25u);
    v2_op_frame_cnot(st, 34u, 25u);
    v2_op_frame_cnot(st, 38u, 25u);
    v2_op_frame_cnot(st, 40u, 25u);
    v2_op_meas_dormant_static(st, 25u, 58u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2636u);
    v2_op_frame_cnot(st, 21u, 19u);
    v2_op_frame_cnot(st, 24u, 19u);
    v2_op_frame_cnot(st, 29u, 19u);
    v2_op_meas_dormant_static(st, 19u, 66u, 0u);
    v2_op_frame_cnot(st, 31u, 26u);
    v2_op_frame_cnot(st, 32u, 26u);
    v2_op_frame_cnot(st, 35u, 26u);
    v2_op_frame_cnot(st, 38u, 26u);
    v2_op_frame_cnot(st, 40u, 26u);
    v2_op_meas_dormant_static(st, 26u, 57u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2637u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 29u, 21u);
    v2_op_frame_cnot(st, 33u, 21u);
    v2_op_frame_cnot(st, 36u, 21u);
    v2_op_frame_cnot(st, 37u, 21u);
    v2_op_meas_dormant_static(st, 21u, 65u, 0u);
    v2_op_frame_cnot(st, 31u, 26u);
    v2_op_frame_cnot(st, 34u, 26u);
    v2_op_meas_dormant_static(st, 26u, 56u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2638u);
    v2_op_meas_dormant_static(st, 37u, 64u, 0u);
    v2_op_meas_dormant_static(st, 41u, 55u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2639u, 24u);
    v2_op_readout_noise(st, readout_noise, 55u);
    v2_op_readout_noise(st, readout_noise, 56u);
    v2_op_readout_noise(st, readout_noise, 57u);
    v2_op_readout_noise(st, readout_noise, 58u);
    v2_op_readout_noise(st, readout_noise, 59u);
    v2_op_readout_noise(st, readout_noise, 60u);
    v2_op_readout_noise(st, readout_noise, 61u);
    v2_op_readout_noise(st, readout_noise, 62u);
    v2_op_readout_noise(st, readout_noise, 63u);
    v2_op_readout_noise(st, readout_noise, 64u);
    v2_op_readout_noise(st, readout_noise, 65u);
    v2_op_readout_noise(st, readout_noise, 66u);
    v2_op_readout_noise(st, readout_noise, 67u);
    v2_op_readout_noise(st, readout_noise, 68u);
    v2_op_readout_noise(st, readout_noise, 69u);
    v2_op_readout_noise(st, readout_noise, 70u);
    v2_op_readout_noise(st, readout_noise, 71u);
    v2_op_readout_noise(st, readout_noise, 72u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2663u);
    v2_op_meas_dormant_random(st, 41u, 228u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2664u, 2u);
    v2_op_frame_cnot(st, 34u, 35u);
    v2_op_frame_cnot(st, 34u, 38u);
    v2_op_frame_cnot(st, 34u, 40u);
    v2_op_frame_cz(st, 34u, 33u);
    v2_op_frame_cz(st, 34u, 37u);
    v2_op_meas_dormant_random(st, 34u, 223u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2666u);
    v2_op_frame_cnot(st, 25u, 31u);
    v2_op_frame_cnot(st, 25u, 38u);
    v2_op_frame_cnot(st, 25u, 40u);
    v2_op_frame_cz(st, 25u, 34u);
    v2_op_frame_cz(st, 25u, 36u);
    v2_op_meas_dormant_random(st, 25u, 211u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2667u);
    v2_op_frame_cnot(st, 7u, 23u);
    v2_op_frame_cnot(st, 7u, 38u);
    v2_op_frame_cnot(st, 7u, 40u);
    v2_op_frame_cz(st, 7u, 24u);
    v2_op_frame_cz(st, 7u, 28u);
    v2_op_frame_cz(st, 7u, 29u);
    v2_op_frame_cz(st, 7u, 33u);
    v2_op_frame_cz(st, 7u, 37u);
    v2_op_meas_dormant_random(st, 7u, 217u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2668u);
    v2_op_frame_cnot(st, 16u, 22u);
    v2_op_frame_cnot(st, 16u, 23u);
    v2_op_meas_dormant_random(st, 16u, 216u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2669u);
    v2_op_frame_cnot(st, 20u, 22u);
    v2_op_frame_cnot(st, 20u, 38u);
    v2_op_frame_cnot(st, 20u, 40u);
    v2_op_frame_cz(st, 20u, 24u);
    v2_op_frame_cz(st, 20u, 28u);
    v2_op_frame_cz(st, 20u, 29u);
    v2_op_frame_cz(st, 20u, 33u);
    v2_op_frame_cz(st, 20u, 37u);
    v2_op_meas_dormant_random(st, 20u, 221u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2670u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_frame_cnot(st, 6u, 8u);
    v2_op_frame_cz(st, 6u, 11u);
    v2_op_frame_cz(st, 6u, 14u);
    v2_op_frame_cz(st, 6u, 15u);
    v2_op_frame_cz(st, 6u, 17u);
    v2_op_frame_cz(st, 6u, 28u);
    v2_op_meas_dormant_random(st, 6u, 214u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2671u);
    v2_op_frame_cnot(st, 4u, 5u);
    v2_op_frame_cnot(st, 4u, 8u);
    v2_op_frame_cz(st, 4u, 2u);
    v2_op_frame_cz(st, 4u, 3u);
    v2_op_frame_cz(st, 4u, 11u);
    v2_op_frame_cz(st, 4u, 14u);
    v2_op_frame_cz(st, 4u, 15u);
    v2_op_frame_cz(st, 4u, 17u);
    v2_op_frame_cz(st, 4u, 28u);
    v2_op_meas_dormant_random(st, 4u, 213u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2672u);
    v2_op_meas_dormant_static(st, 37u, 222u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2673u);
    v2_op_meas_dormant_static(st, 21u, 226u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2674u);
    v2_op_meas_dormant_static(st, 19u, 225u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2675u);
    v2_op_frame_cnot(st, 24u, 21u);
    v2_op_frame_cnot(st, 27u, 21u);
    v2_op_frame_cnot(st, 29u, 21u);
    v2_op_frame_cnot(st, 33u, 21u);
    v2_op_frame_cnot(st, 36u, 21u);
    v2_op_frame_cnot(st, 37u, 21u);
    v2_op_meas_dormant_static(st, 21u, 210u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2676u, 2u);
    v2_op_meas_dormant_static(st, 11u, 224u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2678u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_frame_cnot(st, 14u, 1u);
    v2_op_frame_cnot(st, 28u, 1u);
    v2_op_meas_dormant_static(st, 1u, 220u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2679u, 2u);
    v2_op_frame_cnot(st, 3u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_frame_cnot(st, 13u, 2u);
    v2_op_frame_cnot(st, 14u, 2u);
    v2_op_frame_cnot(st, 15u, 2u);
    v2_op_frame_cnot(st, 17u, 2u);
    v2_op_frame_cnot(st, 28u, 2u);
    v2_op_meas_dormant_static(st, 2u, 212u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2681u, 2u);
    v2_op_meas_dormant_static(st, 18u, 219u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2683u, 5u);
    v2_op_meas_dormant_random(st, 10u, 215u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2688u, 11u);
    v2_op_meas_dormant_random(st, 30u, 227u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2699u, 5u);
    v2_op_meas_dormant_random(st, 39u, 218u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2704u);
    v2_op_apply_pauli(st, pauli_masks, 115u, 210u);
    v2_op_apply_pauli(st, pauli_masks, 116u, 211u);
    v2_op_apply_pauli(st, pauli_masks, 117u, 212u);
    v2_op_apply_pauli(st, pauli_masks, 118u, 213u);
    v2_op_apply_pauli(st, pauli_masks, 119u, 214u);
    v2_op_apply_pauli(st, pauli_masks, 120u, 215u);
    v2_op_apply_pauli(st, pauli_masks, 121u, 216u);
    v2_op_apply_pauli(st, pauli_masks, 122u, 217u);
    v2_op_apply_pauli(st, pauli_masks, 123u, 218u);
    v2_op_apply_pauli(st, pauli_masks, 124u, 219u);
    v2_op_apply_pauli(st, pauli_masks, 125u, 220u);
    v2_op_apply_pauli(st, pauli_masks, 126u, 221u);
    v2_op_apply_pauli(st, pauli_masks, 127u, 222u);
    v2_op_apply_pauli(st, pauli_masks, 128u, 223u);
    v2_op_apply_pauli(st, pauli_masks, 129u, 224u);
    v2_op_apply_pauli(st, pauli_masks, 130u, 225u);
    v2_op_apply_pauli(st, pauli_masks, 131u, 226u);
    v2_op_apply_pauli(st, pauli_masks, 132u, 227u);
    v2_op_apply_pauli(st, pauli_masks, 133u, 228u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2705u, 42u);
    v2_op_frame_cnot(st, 13u, 17u);
    v2_op_frame_cz(st, 13u, 0u);
    v2_op_frame_swap(st, 13u, 1u);
    v2_op_frame_h(st, 1u);
    v2_op_expand_t(st, v, 1u, 1u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2747u);
    v2_op_frame_cnot(st, 15u, 17u);
    v2_op_frame_cz(st, 15u, 1u);
    v2_op_frame_cz(st, 15u, 5u);
    v2_op_frame_swap(st, 15u, 2u);
    v2_op_frame_h(st, 2u);
    v2_op_expand_t(st, v, 2u, 2u, 0);
    v2_op_frame_cnot(st, 27u, 36u);
    v2_op_frame_cz(st, 27u, 0u);
    v2_op_frame_cz(st, 27u, 1u);
    v2_op_frame_cz(st, 27u, 2u);
    v2_op_frame_cz(st, 27u, 5u);
    v2_op_frame_cz(st, 27u, 23u);
    v2_op_frame_cz(st, 27u, 26u);
    v2_op_frame_cz(st, 27u, 31u);
    v2_op_frame_cz(st, 27u, 35u);
    v2_op_frame_swap(st, 27u, 3u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 0);
    v2_op_frame_cnot(st, 14u, 24u);
    v2_op_frame_cnot(st, 14u, 28u);
    v2_op_frame_cnot(st, 14u, 29u);
    v2_op_frame_cz(st, 14u, 1u);
    v2_op_frame_cz(st, 14u, 2u);
    v2_op_frame_cz(st, 14u, 5u);
    v2_op_frame_swap(st, 14u, 4u);
    v2_op_frame_h(st, 4u);
    v2_op_expand_t(st, v, 4u, 4u, 0);
    v2_op_frame_cnot(st, 33u, 36u);
    v2_op_frame_cz(st, 33u, 0u);
    v2_op_frame_cz(st, 33u, 1u);
    v2_op_frame_cz(st, 33u, 2u);
    v2_op_frame_cz(st, 33u, 3u);
    v2_op_frame_cz(st, 33u, 5u);
    v2_op_frame_cz(st, 33u, 23u);
    v2_op_frame_cz(st, 33u, 26u);
    v2_op_frame_cz(st, 33u, 31u);
    v2_op_frame_cz(st, 33u, 32u);
    v2_op_frame_cz(st, 33u, 40u);
    v2_op_frame_swap(st, 33u, 5u);
    v2_op_frame_h(st, 5u);
    v2_op_expand_t(st, v, 5u, 5u, 0);
    v2_op_array_multi_cnot(st, v, 6u, 0u, 46ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_array_t(st, v, 6u, 0u, 0);
    v2_op_frame_cnot(st, 17u, 27u);
    v2_op_frame_cz(st, 17u, 0u);
    v2_op_frame_cz(st, 17u, 1u);
    v2_op_frame_cz(st, 17u, 2u);
    v2_op_frame_cz(st, 17u, 3u);
    v2_op_frame_cz(st, 17u, 5u);
    v2_op_frame_cz(st, 17u, 9u);
    v2_op_frame_cz(st, 17u, 23u);
    v2_op_frame_cz(st, 17u, 26u);
    v2_op_frame_cz(st, 17u, 31u);
    v2_op_frame_cz(st, 17u, 32u);
    v2_op_frame_cz(st, 17u, 33u);
    v2_op_frame_swap(st, 17u, 6u);
    v2_op_frame_h(st, 6u);
    v2_op_expand_t(st, v, 6u, 6u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2748u);
    v2_op_array_multi_cnot(st, v, 7u, 1u, 68ull);
    v2_op_frame_cnot(st, 8u, 1u);
    v2_op_frame_cnot(st, 33u, 1u);
    v2_op_array_t(st, v, 7u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2749u);
    v2_op_frame_cnot(st, 24u, 29u);
    v2_op_frame_cz(st, 24u, 0u);
    v2_op_frame_cz(st, 24u, 2u);
    v2_op_frame_cz(st, 24u, 4u);
    v2_op_frame_cz(st, 24u, 5u);
    v2_op_frame_cz(st, 24u, 6u);
    v2_op_frame_cz(st, 24u, 8u);
    v2_op_frame_cz(st, 24u, 22u);
    v2_op_frame_cz(st, 24u, 26u);
    v2_op_frame_cz(st, 24u, 31u);
    v2_op_frame_cz(st, 24u, 35u);
    v2_op_frame_cz(st, 24u, 40u);
    v2_op_frame_swap(st, 24u, 7u);
    v2_op_frame_h(st, 7u);
    v2_op_expand_t(st, v, 7u, 7u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2750u, 2u);
    v2_op_array_multi_cnot(st, v, 8u, 1u, 192ull);
    v2_op_frame_cnot(st, 8u, 1u);
    v2_op_array_t(st, v, 8u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2752u);
    v2_op_frame_cz(st, 12u, 0u);
    v2_op_frame_cz(st, 12u, 3u);
    v2_op_frame_cz(st, 12u, 5u);
    v2_op_frame_cz(st, 12u, 23u);
    v2_op_frame_cz(st, 12u, 26u);
    v2_op_frame_cz(st, 12u, 31u);
    v2_op_frame_cz(st, 12u, 32u);
    v2_op_frame_swap(st, 12u, 8u);
    v2_op_frame_h(st, 8u);
    v2_op_expand_t(st, v, 8u, 8u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2753u, 3u);
    v2_op_frame_cnot(st, 29u, 36u);
    v2_op_frame_cz(st, 29u, 0u);
    v2_op_frame_cz(st, 29u, 1u);
    v2_op_frame_cz(st, 29u, 2u);
    v2_op_frame_cz(st, 29u, 3u);
    v2_op_frame_cz(st, 29u, 4u);
    v2_op_frame_cz(st, 29u, 5u);
    v2_op_frame_cz(st, 29u, 6u);
    v2_op_frame_cz(st, 29u, 8u);
    v2_op_frame_cz(st, 29u, 12u);
    v2_op_frame_cz(st, 29u, 22u);
    v2_op_frame_cz(st, 29u, 23u);
    v2_op_frame_cz(st, 29u, 40u);
    v2_op_frame_swap(st, 29u, 9u);
    v2_op_frame_h(st, 9u);
    v2_op_expand_t(st, v, 9u, 9u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2756u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 492ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2757u);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 216ull);
    v2_op_frame_cnot(st, 12u, 2u);
    v2_op_frame_cnot(st, 22u, 2u);
    v2_op_frame_cnot(st, 32u, 2u);
    v2_op_frame_cnot(st, 35u, 2u);
    v2_op_frame_cnot(st, 40u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2758u);
    v2_op_array_multi_cnot(st, v, 10u, 1u, 912ull);
    v2_op_frame_cnot(st, 23u, 1u);
    v2_op_frame_cnot(st, 32u, 1u);
    v2_op_frame_cnot(st, 35u, 1u);
    v2_op_frame_cnot(st, 40u, 1u);
    v2_op_array_t(st, v, 10u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2759u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 768ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2760u);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 40ull);
    v2_op_frame_cnot(st, 26u, 2u);
    v2_op_frame_cnot(st, 32u, 2u);
    v2_op_frame_cnot(st, 38u, 2u);
    v2_op_frame_cnot(st, 40u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2761u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 514ull);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2762u, 2u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 58ull);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 2764u, 242u);
    v2_op_array_cnot(st, v, 10u, 0u, 1u);
    v2_op_array_cnot(st, v, 10u, 0u, 2u);
    v2_op_array_cnot(st, v, 10u, 0u, 3u);
    v2_op_array_cnot(st, v, 10u, 0u, 4u);
    v2_op_array_cnot(st, v, 10u, 0u, 5u);
    v2_op_array_cnot(st, v, 10u, 0u, 6u);
    v2_op_array_cnot(st, v, 10u, 0u, 7u);
    v2_op_array_cnot(st, v, 10u, 0u, 8u);
    v2_op_array_cnot(st, v, 10u, 0u, 9u);
    v2_op_frame_cz(st, 0u, 11u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_frame_cz(st, 0u, 15u);
    v2_op_frame_cz(st, 0u, 18u);
    v2_op_frame_cz(st, 0u, 20u);
    v2_op_frame_cz(st, 0u, 21u);
    v2_op_frame_cz(st, 0u, 28u);
    v2_op_frame_cz(st, 0u, 30u);
    v2_op_frame_cz(st, 0u, 34u);
    v2_op_frame_cz(st, 0u, 41u);
    v2_op_swap_meas_interfere(st, v, scratch, 10u, 0u, 9u, 73u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3006u, 40u);
    v2_op_readout_noise(st, readout_noise, 73u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3046u);
    v2_op_meas_dormant_static(st, 9u, 229u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3047u, 41u);
    v2_op_apply_pauli(st, pauli_masks, 134u, 229u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3088u, 299u);
    v2_op_frame_cz(st, 9u, 0u);
    v2_op_frame_cz(st, 9u, 1u);
    v2_op_frame_cz(st, 9u, 2u);
    v2_op_frame_cz(st, 9u, 5u);
    v2_op_frame_cz(st, 9u, 6u);
    v2_op_frame_cz(st, 9u, 7u);
    v2_op_frame_cz(st, 9u, 8u);
    v2_op_frame_cz(st, 9u, 12u);
    v2_op_frame_cz(st, 9u, 22u);
    v2_op_frame_cz(st, 9u, 23u);
    v2_op_frame_cz(st, 9u, 26u);
    v2_op_frame_cz(st, 9u, 32u);
    v2_op_frame_cz(st, 9u, 33u);
    v2_op_frame_cz(st, 9u, 38u);
    v2_op_frame_cz(st, 9u, 40u);
    v2_op_frame_h(st, 9u);
    v2_op_expand_t(st, v, 9u, 9u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3387u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 786ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 252ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 24ull);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 48ull);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_array_cnot(st, v, 10u, 2u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 1);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 100ull);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3388u);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 688ull);
    v2_op_frame_cnot(st, 22u, 2u);
    v2_op_frame_cnot(st, 26u, 2u);
    v2_op_frame_cnot(st, 33u, 2u);
    v2_op_frame_cnot(st, 35u, 2u);
    v2_op_frame_cnot(st, 38u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3389u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 192ull);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3390u, 2u);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 192ull);
    v2_op_frame_cnot(st, 12u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3392u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 384ull);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3393u, 3u);
    v2_op_array_multi_cnot(st, v, 10u, 1u, 404ull);
    v2_op_frame_cnot(st, 23u, 1u);
    v2_op_frame_cnot(st, 32u, 1u);
    v2_op_frame_cnot(st, 35u, 1u);
    v2_op_frame_cnot(st, 40u, 1u);
    v2_op_array_t(st, v, 10u, 1u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3396u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 56ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3397u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 868ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3398u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 970ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3399u);
    v2_op_array_multi_cnot(st, v, 10u, 1u, 56ull);
    v2_op_frame_cnot(st, 31u, 1u);
    v2_op_frame_cnot(st, 32u, 1u);
    v2_op_frame_cnot(st, 38u, 1u);
    v2_op_frame_cnot(st, 40u, 1u);
    v2_op_array_t(st, v, 10u, 1u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3400u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 986ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3401u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 994ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 33u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3402u, 2u);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 406ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3404u, 3u);
    v2_op_meas_dormant_static(st, 18u, 83u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3407u);
    v2_op_meas_dormant_static(st, 15u, 78u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3408u, 3u);
    v2_op_meas_dormant_static(st, 14u, 79u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3411u);
    v2_op_meas_dormant_static(st, 17u, 76u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3412u);
    v2_op_meas_dormant_static(st, 10u, 77u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3413u);
    v2_op_meas_dormant_static(st, 13u, 84u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3414u);
    v2_op_meas_dormant_static(st, 11u, 88u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3415u, 2u);
    v2_op_meas_dormant_static(st, 20u, 85u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3417u);
    v2_op_meas_dormant_static(st, 16u, 74u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3418u);
    v2_op_meas_dormant_static(st, 24u, 75u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3419u);
    v2_op_meas_dormant_static(st, 21u, 80u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3420u);
    v2_op_meas_dormant_static(st, 19u, 89u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3421u);
    v2_op_frame_cnot(st, 36u, 21u);
    v2_op_frame_cnot(st, 37u, 21u);
    v2_op_meas_dormant_static(st, 21u, 90u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3422u);
    v2_op_meas_dormant_static(st, 30u, 91u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3423u);
    v2_op_meas_dormant_static(st, 25u, 81u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3424u);
    v2_op_meas_dormant_static(st, 34u, 87u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3425u, 2u);
    v2_op_meas_dormant_static(st, 37u, 86u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3427u);
    v2_op_meas_dormant_static(st, 39u, 82u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3428u);
    v2_op_meas_dormant_static(st, 41u, 92u, 0u);
    v2_op_readout_noise(st, readout_noise, 74u);
    v2_op_readout_noise(st, readout_noise, 75u);
    v2_op_readout_noise(st, readout_noise, 76u);
    v2_op_readout_noise(st, readout_noise, 77u);
    v2_op_readout_noise(st, readout_noise, 78u);
    v2_op_readout_noise(st, readout_noise, 79u);
    v2_op_readout_noise(st, readout_noise, 80u);
    v2_op_readout_noise(st, readout_noise, 81u);
    v2_op_readout_noise(st, readout_noise, 82u);
    v2_op_readout_noise(st, readout_noise, 83u);
    v2_op_readout_noise(st, readout_noise, 84u);
    v2_op_readout_noise(st, readout_noise, 85u);
    v2_op_readout_noise(st, readout_noise, 86u);
    v2_op_readout_noise(st, readout_noise, 87u);
    v2_op_readout_noise(st, readout_noise, 88u);
    v2_op_readout_noise(st, readout_noise, 89u);
    v2_op_readout_noise(st, readout_noise, 90u);
    v2_op_readout_noise(st, readout_noise, 91u);
    v2_op_readout_noise(st, readout_noise, 92u);
    v2_op_observable(st, observable_offsets, observable_targets, 0u, 0u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3429u, 26u);
    v2_op_frame_cnot(st, 33u, 12u);
    v2_op_meas_dormant_static(st, 12u, 96u, 0u);
    v2_op_array_cnot(st, v, 10u, 6u, 9u);
    v2_op_frame_cz(st, 6u, 11u);
    v2_op_frame_cz(st, 6u, 28u);
    v2_op_swap_meas_interfere(st, v, scratch, 10u, 6u, 9u, 93u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3455u);
    v2_op_frame_cnot(st, 33u, 12u);
    v2_op_meas_dormant_static(st, 12u, 102u, 0u);
    v2_op_array_cnot(st, v, 9u, 2u, 6u);
    v2_op_array_cnot(st, v, 9u, 2u, 7u);
    v2_op_frame_cz(st, 2u, 9u);
    v2_op_swap_meas_interfere(st, v, scratch, 9u, 2u, 8u, 99u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3456u, 7u);
    v2_op_frame_cnot(st, 32u, 22u);
    v2_op_frame_cnot(st, 35u, 22u);
    v2_op_frame_cnot(st, 40u, 22u);
    v2_op_meas_dormant_static(st, 22u, 108u, 0u);
    v2_op_array_cnot(st, v, 8u, 3u, 4u);
    v2_op_array_cnot(st, v, 8u, 3u, 6u);
    v2_op_array_cnot(st, v, 8u, 3u, 7u);
    v2_op_frame_cz(st, 3u, 8u);
    v2_op_frame_cz(st, 3u, 9u);
    v2_op_frame_cz(st, 3u, 28u);
    v2_op_swap_meas_interfere(st, v, scratch, 8u, 3u, 7u, 105u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3463u);
    v2_op_frame_cnot(st, 32u, 23u);
    v2_op_frame_cnot(st, 35u, 23u);
    v2_op_frame_cnot(st, 40u, 23u);
    v2_op_meas_dormant_static(st, 23u, 97u, 0u);
    v2_op_array_cnot(st, v, 7u, 2u, 4u);
    v2_op_array_cnot(st, v, 7u, 2u, 6u);
    v2_op_frame_cz(st, 2u, 8u);
    v2_op_frame_cz(st, 2u, 9u);
    v2_op_frame_cz(st, 2u, 13u);
    v2_op_frame_cz(st, 2u, 28u);
    v2_op_swap_meas_interfere(st, v, scratch, 7u, 2u, 6u, 94u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3464u);
    v2_op_frame_cnot(st, 32u, 23u);
    v2_op_frame_cnot(st, 35u, 23u);
    v2_op_frame_cnot(st, 40u, 23u);
    v2_op_meas_dormant_static(st, 23u, 103u, 0u);
    v2_op_array_cnot(st, v, 6u, 1u, 2u);
    v2_op_array_cnot(st, v, 6u, 1u, 4u);
    v2_op_frame_cz(st, 1u, 6u);
    v2_op_frame_cz(st, 1u, 8u);
    v2_op_frame_cz(st, 1u, 9u);
    v2_op_frame_cz(st, 1u, 11u);
    v2_op_swap_meas_interfere(st, v, scratch, 6u, 1u, 5u, 100u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3465u, 2u);
    v2_op_frame_cnot(st, 31u, 26u);
    v2_op_frame_cnot(st, 32u, 26u);
    v2_op_frame_cnot(st, 35u, 26u);
    v2_op_frame_cnot(st, 38u, 26u);
    v2_op_frame_cnot(st, 40u, 26u);
    v2_op_meas_dormant_static(st, 26u, 109u, 0u);
    v2_op_array_cnot(st, v, 5u, 2u, 4u);
    v2_op_frame_cz(st, 2u, 5u);
    v2_op_frame_cz(st, 2u, 6u);
    v2_op_frame_cz(st, 2u, 8u);
    v2_op_frame_cz(st, 2u, 9u);
    v2_op_frame_cz(st, 2u, 11u);
    v2_op_frame_cz(st, 2u, 19u);
    v2_op_frame_cz(st, 2u, 36u);
    v2_op_frame_cz(st, 2u, 37u);
    v2_op_swap_meas_interfere(st, v, scratch, 5u, 2u, 4u, 106u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3467u, 2u);
    v2_op_frame_cnot(st, 31u, 26u);
    v2_op_frame_cnot(st, 35u, 26u);
    v2_op_meas_dormant_static(st, 26u, 98u, 0u);
    v2_op_array_cnot(st, v, 4u, 1u, 3u);
    v2_op_frame_cz(st, 1u, 4u);
    v2_op_frame_cz(st, 1u, 5u);
    v2_op_frame_cz(st, 1u, 6u);
    v2_op_frame_cz(st, 1u, 7u);
    v2_op_frame_cz(st, 1u, 11u);
    v2_op_frame_cz(st, 1u, 19u);
    v2_op_frame_cz(st, 1u, 36u);
    v2_op_frame_cz(st, 1u, 37u);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 1u, 3u, 95u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3469u);
    v2_op_frame_cnot(st, 35u, 32u);
    v2_op_frame_cnot(st, 38u, 32u);
    v2_op_frame_cnot(st, 40u, 32u);
    v2_op_meas_dormant_static(st, 32u, 104u, 0u);
    v2_op_array_cnot(st, v, 3u, 0u, 1u);
    v2_op_array_cnot(st, v, 3u, 0u, 2u);
    v2_op_frame_cz(st, 0u, 3u);
    v2_op_frame_cz(st, 0u, 6u);
    v2_op_frame_cz(st, 0u, 8u);
    v2_op_frame_cz(st, 0u, 15u);
    v2_op_frame_cz(st, 0u, 18u);
    v2_op_frame_cz(st, 0u, 19u);
    v2_op_frame_cz(st, 0u, 20u);
    v2_op_frame_cz(st, 0u, 30u);
    v2_op_frame_cz(st, 0u, 34u);
    v2_op_frame_cz(st, 0u, 41u);
    v2_op_swap_meas_interfere(st, v, scratch, 3u, 0u, 2u, 101u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 3470u);
    v2_op_frame_cnot(st, 35u, 32u);
    v2_op_frame_cnot(st, 38u, 32u);
    v2_op_frame_cnot(st, 40u, 32u);
    v2_op_meas_dormant_static(st, 32u, 110u, 0u);
    v2_op_array_cnot(st, v, 2u, 0u, 1u);
    v2_op_frame_cz(st, 0u, 2u);
    v2_op_frame_cz(st, 0u, 3u);
    v2_op_frame_cz(st, 0u, 4u);
    v2_op_frame_cz(st, 0u, 5u);
    v2_op_frame_cz(st, 0u, 6u);
    v2_op_frame_cz(st, 0u, 7u);
    v2_op_frame_cz(st, 0u, 11u);
    v2_op_frame_cz(st, 0u, 21u);
    v2_op_frame_cz(st, 0u, 37u);
    v2_op_swap_meas_interfere(st, v, scratch, 2u, 0u, 1u, 107u, 0u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_frame_swap(st, 9u, 1u);
    v2_op_frame_h(st, 1u);
    v2_op_expand_t(st, v, 1u, 1u, 1);
    v2_op_frame_cz(st, 7u, 0u);
    v2_op_frame_cz(st, 7u, 1u);
    v2_op_frame_cz(st, 7u, 33u);
    v2_op_frame_swap(st, 7u, 2u);
    v2_op_frame_h(st, 2u);
    v2_op_expand_t(st, v, 2u, 2u, 1);
    v2_op_frame_cz(st, 3u, 0u);
    v2_op_frame_cz(st, 3u, 1u);
    v2_op_frame_cz(st, 3u, 2u);
    v2_op_frame_cz(st, 3u, 33u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 1);
    v2_op_frame_cnot(st, 6u, 7u);
    v2_op_frame_cz(st, 6u, 0u);
    v2_op_frame_cz(st, 6u, 1u);
    v2_op_frame_cz(st, 6u, 2u);
    v2_op_frame_cz(st, 6u, 33u);
    v2_op_frame_swap(st, 6u, 4u);
    v2_op_frame_h(st, 4u);
    v2_op_expand_t(st, v, 4u, 4u, 1);
    v2_op_frame_cz(st, 9u, 0u);
    v2_op_frame_cz(st, 9u, 1u);
    v2_op_frame_cz(st, 9u, 2u);
    v2_op_frame_cz(st, 9u, 3u);
    v2_op_frame_cz(st, 9u, 33u);
    v2_op_frame_swap(st, 9u, 5u);
    v2_op_frame_h(st, 5u);
    v2_op_expand_t(st, v, 5u, 5u, 1);
    v2_op_array_multi_cnot(st, v, 6u, 0u, 46ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_array_t(st, v, 6u, 0u, 1);
    v2_op_frame_cz(st, 8u, 1u);
    v2_op_frame_swap(st, 8u, 6u);
    v2_op_frame_h(st, 6u);
    v2_op_expand_t(st, v, 6u, 6u, 0);
    v2_op_array_multi_cnot(st, v, 7u, 1u, 68ull);
    v2_op_frame_cnot(st, 12u, 1u);
    v2_op_frame_cnot(st, 33u, 1u);
    v2_op_array_t(st, v, 7u, 1u, 0);
    v2_op_frame_cz(st, 7u, 2u);
    v2_op_frame_cz(st, 7u, 4u);
    v2_op_frame_cz(st, 7u, 6u);
    v2_op_frame_cz(st, 7u, 33u);
    v2_op_frame_h(st, 7u);
    v2_op_expand_t(st, v, 7u, 7u, 0);
    v2_op_array_multi_cnot(st, v, 8u, 1u, 192ull);
    v2_op_frame_cnot(st, 12u, 1u);
    v2_op_array_t(st, v, 8u, 1u, 0);
    v2_op_frame_cz(st, 9u, 0u);
    v2_op_frame_cz(st, 9u, 2u);
    v2_op_frame_cz(st, 9u, 3u);
    v2_op_frame_cz(st, 9u, 5u);
    v2_op_frame_cz(st, 9u, 6u);
    v2_op_frame_cz(st, 9u, 7u);
    v2_op_frame_cz(st, 9u, 12u);
    v2_op_frame_cz(st, 9u, 22u);
    v2_op_frame_cz(st, 9u, 26u);
    v2_op_frame_cz(st, 9u, 32u);
    v2_op_frame_swap(st, 9u, 8u);
    v2_op_frame_h(st, 8u);
    v2_op_expand_t(st, v, 8u, 8u, 0);
    v2_op_frame_cz(st, 9u, 8u);
    v2_op_frame_cz(st, 9u, 31u);
    v2_op_frame_cz(st, 9u, 32u);
    v2_op_frame_cz(st, 9u, 38u);
    v2_op_frame_cz(st, 9u, 40u);
    v2_op_frame_h(st, 9u);
    v2_op_expand_t(st, v, 9u, 9u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 492ull);
    v2_op_frame_cnot(st, 12u, 0u);
    v2_op_frame_cnot(st, 22u, 0u);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 216ull);
    v2_op_frame_cnot(st, 12u, 2u);
    v2_op_frame_cnot(st, 22u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 1u, 912ull);
    v2_op_frame_cnot(st, 23u, 1u);
    v2_op_frame_cnot(st, 32u, 1u);
    v2_op_frame_cnot(st, 35u, 1u);
    v2_op_frame_cnot(st, 40u, 1u);
    v2_op_array_t(st, v, 10u, 1u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 768ull);
    v2_op_frame_cnot(st, 23u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 2u, 40ull);
    v2_op_frame_cnot(st, 26u, 2u);
    v2_op_array_t(st, v, 10u, 2u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 514ull);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 31u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_array_multi_cnot(st, v, 10u, 0u, 58ull);
    v2_op_frame_cnot(st, 26u, 0u);
    v2_op_frame_cnot(st, 32u, 0u);
    v2_op_frame_cnot(st, 35u, 0u);
    v2_op_frame_cnot(st, 38u, 0u);
    v2_op_frame_cnot(st, 40u, 0u);
    v2_op_array_t(st, v, 10u, 0u, 0);
    v2_op_array_cnot(st, v, 10u, 0u, 1u);
    v2_op_array_cnot(st, v, 10u, 0u, 2u);
    v2_op_array_cnot(st, v, 10u, 0u, 3u);
    v2_op_array_cnot(st, v, 10u, 0u, 4u);
    v2_op_array_cnot(st, v, 10u, 0u, 5u);
    v2_op_array_cnot(st, v, 10u, 0u, 6u);
    v2_op_array_cnot(st, v, 10u, 0u, 7u);
    v2_op_array_cnot(st, v, 10u, 0u, 8u);
    v2_op_array_cnot(st, v, 10u, 0u, 9u);
    v2_op_array_multi_cz(st, v, 10u, 0u, 798ull);
    v2_op_frame_cz(st, 0u, 12u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_frame_cz(st, 0u, 15u);
    v2_op_frame_cz(st, 0u, 19u);
    v2_op_frame_cz(st, 0u, 32u);
    v2_op_frame_cz(st, 0u, 33u);
    v2_op_frame_cz(st, 0u, 36u);
    v2_op_frame_cz(st, 0u, 37u);
    v2_op_frame_cz(st, 0u, 38u);
    v2_op_array_s(st, v, 10u, 0u, 0);
    v2_op_swap_meas_interfere(st, v, scratch, 10u, 0u, 9u, 111u, 0u);
    v2_op_observable(st, observable_offsets, observable_targets, 1u, 0u);
    v2_shot_aggregate(st, block_counts, num_observables, expected_obs_mask);
}

extern __attribute__((address_space(3))) CV2Complex lds_v[V2_MAX_AMP];
extern __attribute__((address_space(3))) CV2Complex lds_red_scratch[V2_SCRATCH_AMP];
extern __attribute__((address_space(3))) V2State lds_state;
__attribute__((amdgpu_kernel, visibility("default")))
void clifft_v2_spec(const CV2Instr* instrs, u32 num_instrs, u32 peak_rank,
    u32 total_meas_slots, u32 num_observables,
    u64 seed, u64 shot_offset, u64 shots,
    CV2BlockCounts* block_counts,
    const CV2FusedU2Entry* fused_u2, const CV2FusedU4Entry* fused_u4,
    const u32* observable_offsets, const u32* observable_targets,
    const CV2NoiseSite* noise_sites, const CV2Channel* noise_channels,
    const double* noise_hazards, u32 num_noise_sites, u32 expected_obs_mask,
    const CV2Mask* pauli_masks, const CV2ReadoutNoise* readout_noise,
    const u32* detector_offsets, const u32* detector_targets) {
    (void)peak_rank; (void)num_instrs; (void)instrs; (void)total_meas_slots;
    u64 shot_id = shot_offset + (u64)v2_bid();
    if (shot_id >= shots) return;
    spec_body((V2State*)&lds_state, (CV2Complex*)lds_v, (CV2Complex*)lds_red_scratch,
              V2_MAX_AMP, shot_id, num_observables, seed, block_counts, fused_u2, fused_u4,
                  observable_offsets, observable_targets, noise_sites, noise_channels,
                  noise_hazards, num_noise_sites, pauli_masks, readout_noise,
                  detector_offsets, detector_targets, expected_obs_mask);
}
