#define V2_REGISTER 1
#define V2_NOISE_ATTR __attribute__((noinline))
#include "clifft/gpu/mlir/v2/v2_ops.h"

static void spec_body(V2State* st, CV2Complex* v, CV2Complex* scratch,
                      u32 amp_capacity, u64 shot_id, u32 num_observables, u64 seed,
                      CV2BlockCounts* block_counts,
                      const CV2FusedU2Entry* fused_u2, const CV2FusedU4Entry* fused_u4,
                      const u32* observable_offsets, const u32* observable_targets,
                      const CV2NoiseSite* noise_sites, const CV2Channel* noise_channels,
                      const double* noise_hazards, u32 num_noise_sites,
                      const CV2Mask* pauli_masks, const CV2ReadoutNoise* readout_noise,
                      const u32* detector_offsets, const u32* detector_targets,
                      u32 expected_obs_mask) {
    v2_shot_init(st, v, amp_capacity, shot_id, num_observables, seed, noise_hazards, num_noise_sites);
    v2_op_meas_dormant_static(st, 6u, 33u, 0u);
    v2_op_meas_dormant_static(st, 8u, 32u, 0u);
    v2_op_meas_dormant_static(st, 11u, 31u, 0u);
    v2_op_meas_dormant_random(st, 13u, 30u, 0u);
    v2_op_meas_dormant_random(st, 5u, 29u, 0u);
    v2_op_meas_dormant_random(st, 0u, 28u, 0u);
    v2_op_meas_dormant_random(st, 14u, 27u, 0u);
    v2_op_meas_dormant_random(st, 4u, 26u, 0u);
    v2_op_meas_dormant_random(st, 2u, 25u, 0u);
    v2_op_meas_dormant_random(st, 3u, 24u, 0u);
    v2_op_meas_dormant_random(st, 12u, 23u, 0u);
    v2_op_meas_dormant_random(st, 10u, 22u, 0u);
    v2_op_meas_dormant_random(st, 7u, 21u, 0u);
    v2_op_apply_pauli(st, pauli_masks, 0u, 21u);
    v2_op_apply_pauli(st, pauli_masks, 1u, 22u);
    v2_op_apply_pauli(st, pauli_masks, 2u, 23u);
    v2_op_apply_pauli(st, pauli_masks, 3u, 24u);
    v2_op_apply_pauli(st, pauli_masks, 4u, 25u);
    v2_op_apply_pauli(st, pauli_masks, 5u, 26u);
    v2_op_apply_pauli(st, pauli_masks, 6u, 27u);
    v2_op_apply_pauli(st, pauli_masks, 7u, 28u);
    v2_op_apply_pauli(st, pauli_masks, 8u, 29u);
    v2_op_apply_pauli(st, pauli_masks, 9u, 30u);
    v2_op_apply_pauli(st, pauli_masks, 10u, 31u);
    v2_op_apply_pauli(st, pauli_masks, 11u, 32u);
    v2_op_apply_pauli(st, pauli_masks, 12u, 33u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 0u, 131u);
    v2_op_frame_cnot(st, 3u, 10u);
    v2_op_frame_cnot(st, 3u, 12u);
    v2_op_frame_cz(st, 3u, 6u);
    v2_op_frame_cz(st, 3u, 8u);
    v2_op_frame_swap(st, 3u, 0u);
    v2_op_frame_h(st, 0u);
    v2_op_expand_t(st, v, 0u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 131u, 57u);
    v2_op_meas_dormant_static(st, 3u, 34u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 188u);
    v2_op_meas_dormant_static(st, 5u, 36u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 189u, 3u);
    v2_op_frame_cnot(st, 2u, 7u);
    v2_op_frame_cnot(st, 2u, 10u);
    v2_op_frame_cz(st, 2u, 6u);
    v2_op_meas_dormant_random(st, 2u, 37u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 192u, 2u);
    v2_op_frame_cnot(st, 4u, 7u);
    v2_op_frame_cnot(st, 4u, 12u);
    v2_op_frame_cz(st, 4u, 8u);
    v2_op_meas_dormant_random(st, 4u, 39u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 194u);
    v2_op_meas_dormant_static(st, 9u, 40u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 195u, 2u);
    v2_op_meas_dormant_static(st, 14u, 35u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 197u, 3u);
    v2_op_frame_cnot(st, 7u, 10u);
    v2_op_frame_cnot(st, 7u, 12u);
    v2_op_frame_cnot(st, 7u, 13u);
    v2_op_frame_cz(st, 7u, 11u);
    v2_op_meas_dormant_random(st, 7u, 38u, 0u);
    v2_op_apply_pauli(st, pauli_masks, 13u, 34u);
    v2_op_apply_pauli(st, pauli_masks, 14u, 35u);
    v2_op_apply_pauli(st, pauli_masks, 15u, 36u);
    v2_op_apply_pauli(st, pauli_masks, 16u, 37u);
    v2_op_apply_pauli(st, pauli_masks, 17u, 38u);
    v2_op_apply_pauli(st, pauli_masks, 18u, 39u);
    v2_op_apply_pauli(st, pauli_masks, 19u, 40u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 200u, 92u);
    v2_op_meas_dormant_static(st, 10u, 4u, 0u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_meas_dormant_static(st, 2u, 0u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 292u);
    v2_op_meas_dormant_static(st, 12u, 6u, 0u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_frame_cnot(st, 8u, 2u);
    v2_op_frame_cnot(st, 9u, 2u);
    v2_op_meas_dormant_static(st, 2u, 2u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 293u);
    v2_op_frame_cnot(st, 12u, 10u);
    v2_op_frame_cnot(st, 13u, 10u);
    v2_op_meas_dormant_static(st, 10u, 5u, 0u);
    v2_op_meas_dormant_static(st, 11u, 1u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 294u, 4u);
    v2_op_meas_dormant_static(st, 9u, 3u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 298u, 5u);
    v2_op_readout_noise(st, readout_noise, 0u);
    v2_op_readout_noise(st, readout_noise, 1u);
    v2_op_readout_noise(st, readout_noise, 2u);
    v2_op_readout_noise(st, readout_noise, 3u);
    v2_op_readout_noise(st, readout_noise, 4u);
    v2_op_readout_noise(st, readout_noise, 5u);
    v2_op_readout_noise(st, readout_noise, 6u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 303u);
    v2_op_frame_cz(st, 8u, 10u);
    v2_op_frame_cz(st, 8u, 12u);
    v2_op_frame_cz(st, 8u, 13u);
    v2_op_meas_dormant_random(st, 8u, 43u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 304u);
    v2_op_frame_cnot(st, 7u, 11u);
    v2_op_frame_cz(st, 7u, 14u);
    v2_op_meas_dormant_random(st, 7u, 41u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 305u);
    v2_op_frame_cnot(st, 2u, 0u);
    v2_op_frame_cnot(st, 2u, 4u);
    v2_op_frame_cnot(st, 2u, 6u);
    v2_op_frame_cz(st, 2u, 5u);
    v2_op_frame_cz(st, 2u, 8u);
    v2_op_frame_cz(st, 2u, 10u);
    v2_op_frame_cz(st, 2u, 13u);
    v2_op_meas_dormant_random(st, 2u, 45u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 306u, 2u);
    v2_op_frame_cnot(st, 12u, 10u);
    v2_op_frame_cnot(st, 13u, 10u);
    v2_op_meas_dormant_static(st, 10u, 44u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 308u);
    v2_op_frame_cnot(st, 12u, 10u);
    v2_op_frame_cnot(st, 13u, 10u);
    v2_op_meas_dormant_static(st, 10u, 42u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 309u, 3u);
    v2_op_meas_dormant_random(st, 1u, 46u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 312u, 6u);
    v2_op_apply_pauli(st, pauli_masks, 20u, 41u);
    v2_op_apply_pauli(st, pauli_masks, 21u, 42u);
    v2_op_apply_pauli(st, pauli_masks, 22u, 43u);
    v2_op_apply_pauli(st, pauli_masks, 23u, 44u);
    v2_op_apply_pauli(st, pauli_masks, 24u, 45u);
    v2_op_apply_pauli(st, pauli_masks, 25u, 46u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 318u, 15u);
    v2_op_frame_swap(st, 3u, 1u);
    v2_op_frame_h(st, 1u);
    v2_op_expand_t(st, v, 1u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 333u);
    v2_op_frame_cz(st, 5u, 0u);
    v2_op_frame_cz(st, 5u, 1u);
    v2_op_frame_swap(st, 5u, 2u);
    v2_op_frame_h(st, 2u);
    v2_op_expand_t(st, v, 2u, 2u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 334u);
    v2_op_frame_cz(st, 14u, 0u);
    v2_op_frame_cz(st, 14u, 2u);
    v2_op_frame_cz(st, 14u, 4u);
    v2_op_frame_cz(st, 14u, 6u);
    v2_op_frame_cz(st, 14u, 9u);
    v2_op_frame_cz(st, 14u, 11u);
    v2_op_frame_swap(st, 14u, 3u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 335u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 9u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 336u);
    v2_op_array_multi_cnot(st, v, 4u, 1u, 12ull);
    v2_op_frame_cnot(st, 4u, 1u);
    v2_op_frame_cnot(st, 6u, 1u);
    v2_op_array_t(st, v, 4u, 1u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 337u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 12ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 338u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 10ull);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 339u, 44u);
    v2_op_array_cnot(st, v, 4u, 0u, 1u);
    v2_op_array_cnot(st, v, 4u, 0u, 2u);
    v2_op_array_cnot(st, v, 4u, 0u, 3u);
    v2_op_frame_cz(st, 0u, 5u);
    v2_op_frame_cz(st, 0u, 7u);
    v2_op_frame_cz(st, 0u, 10u);
    v2_op_frame_cz(st, 0u, 12u);
    v2_op_frame_cz(st, 0u, 14u);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 0u, 3u, 7u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 383u, 13u);
    v2_op_readout_noise(st, readout_noise, 7u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 396u);
    v2_op_meas_dormant_static(st, 3u, 47u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 397u, 14u);
    v2_op_apply_pauli(st, pauli_masks, 26u, 47u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 411u, 63u);
    v2_op_frame_cz(st, 3u, 0u);
    v2_op_frame_cz(st, 3u, 1u);
    v2_op_frame_cz(st, 3u, 2u);
    v2_op_frame_cz(st, 3u, 4u);
    v2_op_frame_cz(st, 3u, 6u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 474u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 10ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 475u);
    v2_op_array_multi_cnot(st, v, 4u, 1u, 12ull);
    v2_op_frame_cnot(st, 4u, 1u);
    v2_op_frame_cnot(st, 6u, 1u);
    v2_op_array_t(st, v, 4u, 1u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 476u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 14ull);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 477u);
    v2_op_array_cnot(st, v, 4u, 2u, 0u);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 478u);
    v2_op_array_cnot(st, v, 4u, 3u, 2u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_array_t(st, v, 4u, 2u, 0);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 479u);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 480u, 2u);
    v2_op_meas_dormant_static(st, 14u, 13u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 482u);
    v2_op_frame_cnot(st, 12u, 10u);
    v2_op_frame_cnot(st, 13u, 10u);
    v2_op_meas_dormant_static(st, 10u, 11u, 0u);
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 483u, 3u);
    v2_op_meas_dormant_static(st, 8u, 10u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 486u);
    v2_op_meas_dormant_static(st, 5u, 12u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 487u);
    v2_op_frame_cnot(st, 12u, 10u);
    v2_op_frame_cnot(st, 13u, 10u);
    v2_op_meas_dormant_static(st, 10u, 9u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 488u);
    v2_op_meas_dormant_static(st, 7u, 8u, 0u);
    v2_op_readout_noise(st, readout_noise, 8u);
    v2_op_readout_noise(st, readout_noise, 9u);
    v2_op_readout_noise(st, readout_noise, 10u);
    v2_op_readout_noise(st, readout_noise, 11u);
    v2_op_readout_noise(st, readout_noise, 12u);
    v2_op_readout_noise(st, readout_noise, 13u);
    v2_op_observable(st, observable_offsets, observable_targets, 0u, 0u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_noise_block(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 489u, 13u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_meas_dormant_static(st, 4u, 16u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 502u);
    v2_op_frame_cnot(st, 6u, 4u);
    v2_op_meas_dormant_static(st, 4u, 18u, 0u);
    v2_op_noise(st, noise_sites, noise_channels, noise_hazards, num_noise_sites, 503u);
    v2_op_meas_dormant_static(st, 11u, 20u, 0u);
    v2_op_array_t(st, v, 4u, 3u, 0);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 12ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_array_t(st, v, 4u, 1u, 0);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 12ull);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_array_t(st, v, 4u, 2u, 0);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 6ull);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 0);
    v2_op_array_cnot(st, v, 4u, 0u, 1u);
    v2_op_array_cnot(st, v, 4u, 0u, 2u);
    v2_op_array_cnot(st, v, 4u, 0u, 3u);
    v2_op_array_multi_cz(st, v, 4u, 0u, 14ull);
    v2_op_frame_cz(st, 0u, 4u);
    v2_op_frame_cz(st, 0u, 5u);
    v2_op_frame_cz(st, 0u, 7u);
    v2_op_frame_cz(st, 0u, 10u);
    v2_op_frame_cz(st, 0u, 11u);
    v2_op_frame_cz(st, 0u, 14u);
    v2_op_array_s(st, v, 4u, 0u, 0);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 0u, 3u, 14u, 0u);
    v2_op_frame_cz(st, 3u, 0u);
    v2_op_frame_h(st, 3u);
    v2_op_expand_t(st, v, 3u, 3u, 1);
    v2_op_array_cnot(st, v, 4u, 3u, 2u);
    v2_op_frame_cnot(st, 4u, 2u);
    v2_op_frame_cnot(st, 6u, 2u);
    v2_op_frame_cnot(st, 11u, 2u);
    v2_op_array_t(st, v, 4u, 2u, 1);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 10ull);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_array_cnot(st, v, 4u, 3u, 1u);
    v2_op_frame_cnot(st, 6u, 1u);
    v2_op_frame_cnot(st, 11u, 1u);
    v2_op_array_t(st, v, 4u, 1u, 1);
    v2_op_array_multi_cnot(st, v, 4u, 0u, 12ull);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_array_t(st, v, 4u, 0u, 1);
    v2_op_array_cnot(st, v, 4u, 0u, 2u);
    v2_op_array_cnot(st, v, 4u, 0u, 3u);
    v2_op_frame_cz(st, 0u, 10u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_swap_meas_interfere(st, v, scratch, 4u, 0u, 3u, 15u, 0u);
    v2_op_array_cnot(st, v, 3u, 1u, 0u);
    v2_op_frame_cnot(st, 6u, 0u);
    v2_op_array_t(st, v, 3u, 0u, 1);
    v2_op_array_cnot(st, v, 3u, 0u, 1u);
    v2_op_array_cnot(st, v, 3u, 0u, 2u);
    v2_op_frame_cz(st, 0u, 10u);
    v2_op_frame_cz(st, 0u, 12u);
    v2_op_frame_cz(st, 0u, 13u);
    v2_op_swap_meas_interfere(st, v, scratch, 3u, 0u, 2u, 17u, 0u);
    v2_op_array_cnot(st, v, 2u, 1u, 0u);
    v2_op_frame_cnot(st, 4u, 0u);
    v2_op_frame_cnot(st, 11u, 0u);
    v2_op_array_t(st, v, 2u, 0u, 1);
    v2_op_array_cnot(st, v, 2u, 0u, 1u);
    v2_op_array_cz(st, v, 2u, 0u, 1u);
    v2_op_frame_cz(st, 0u, 2u);
    v2_op_frame_cz(st, 0u, 3u);
    v2_op_frame_cz(st, 0u, 4u);
    v2_op_frame_cz(st, 0u, 6u);
    v2_op_array_s(st, v, 2u, 0u, 0);
    v2_op_swap_meas_interfere(st, v, scratch, 2u, 0u, 1u, 19u, 0u);
    v2_op_observable(st, observable_offsets, observable_targets, 1u, 0u);
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_op_detector();
    v2_shot_aggregate(st, block_counts, num_observables, expected_obs_mask);
}

#define V2_REG_MAX_AMP 16
__attribute__((amdgpu_kernel, visibility("default")))
void clifft_v2_spec(const CV2Instr* instrs, u32 num_instrs, u32 peak_rank,
    u32 total_meas_slots, u32 num_observables,
    u64 seed, u64 shot_offset, u64 shots,
    CV2BlockCounts* block_counts,
    const CV2FusedU2Entry* fused_u2, const CV2FusedU4Entry* fused_u4,
    const u32* observable_offsets, const u32* observable_targets,
    const CV2NoiseSite* noise_sites, const CV2Channel* noise_channels,
    const double* noise_hazards, u32 num_noise_sites, u32 expected_obs_mask,
    const CV2Mask* pauli_masks, const CV2ReadoutNoise* readout_noise,
    const u32* detector_offsets, const u32* detector_targets) {
    (void)peak_rank; (void)num_instrs; (void)instrs; (void)total_meas_slots;
    u64 shot_id = shot_offset + ((u64)v2_bid() * 256ul + (u64)__builtin_amdgcn_workitem_id_x());
    if (shot_id >= shots) return;
    V2State st; CV2Complex vloc[V2_REG_MAX_AMP]; CV2Complex sloc[V2_REG_MAX_AMP/2];
    spec_body(&st, vloc, sloc, V2_REG_MAX_AMP, shot_id, num_observables, seed, block_counts, fused_u2, fused_u4,
                  observable_offsets, observable_targets, noise_sites, noise_channels,
                  noise_hazards, num_noise_sites, pauli_masks, readout_noise,
                  detector_offsets, detector_targets, expected_obs_mask);
}
